framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr
        enabled: false  # Désactive complètement la traduction
        providers:
