# Commentez ou supprimez si présent :
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Supprimez complètement cette partie qui force la redirection vers /en
root_route_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: /fr
        permanent: true